default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  database: <%= ENV.fetch("RAILS_DB_NAME") %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
